# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - NextReadsFrontend

on:
  push:
    branches:
      - Deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://nextreadsfrontend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_12d171b4051f4ee2aaf0ca3ebc89c755 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_730f4a7bfa5b44b2a8c4115502be5d33 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nextreadsfrontend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_12d171b4051f4ee2aaf0ca3ebc89c755 }}/next-reads-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NextReadsFrontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f832daa6fbfe48aba6d6a5e1436a8f7f }}
        images: 'nextreadsfrontend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_12d171b4051f4ee2aaf0ca3ebc89c755 }}/next-reads-frontend:${{ github.sha }}'